# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('langevin_photo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='titre_bouton_droit',
            field=models.CharField(default=b'', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='titre_bouton_gauche',
            field=models.CharField(default=b'', max_length=255),
        ),
    ]
