# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 15:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0018_remove_rendition_filter'),
        ('langevin_photo', '0002_auto_20170306_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='photo_background',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
