# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 16:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('langevin_photo', '0004_albumlistpage_albumpage_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='url',
        ),
    ]
