# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 18:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('langevin_photo', '0006_auto_20170306_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='albumlistpage',
            name='nom_categorie',
        ),
    ]
