# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('langevin_photo', '0008_aboutpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='albumpage',
            name='body_cacher',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='albumpage',
            name='body',
            field=models.CharField(max_length=150),
        ),
    ]
