# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('langevin_photo', '0010_quadpage_quadphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='quadpage',
            name='titre_pdf',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
